apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credential
  namespace: fast-api
spec:
  encryptedData:
    .dockerconfigjson: AgBQwr9xnPuTAHQWZZV/TigFt4tQpuPkOoRN5FrzcRmjZAfW2oaJTQW4tN7qSPv5wBIYX8olUmokuYugfmHqiiKG7nuNM3uzlZ5uTvjVMHaKqrG212HDYGJKibGRo1j+PdJJ2eNLPj7VyyLiiLcPQ1/mkBHfAz2B12nifqIIbUsJzdITUZcqU4tzDfo2oGrV4BK7xgvZqlNS9DPWJiyxX75O31tqYf6MJujXBfWg3k7a/DhAyGqdI2wc1mj7dKyo+Bpp0nWKAiKf24UxHtGyszzLY2m50RFL42G6i65T2e9ojvNNlcgIAbqRj7flyOt3bLHAwmLkceczjR4vcB9TZs708TS7wKSIqy/4myEVXI0InYCF7oPh2C5kCor7rD5hz02YgyZXM24j97U9CsQhjDpchlfgRXeTir0Ne1LIhPmkd8nobVYp+RzWeXsr0DaTjVAl8oY5OjuhAaNVaW36t9+9HXwrryisELjqxC4XtNnF3jHE/x3LybxrcEFtOJ1dL1apUYqzQ25JyZbPJqTxVGp9bla3XbqYaGEQuLaTZumEdBO9OYFiQngKagHIrMC8BuRq6WmcolHXBsn+B6WiOClQNlRxxx5JcKnTmqmr4rmo4ABs8gugUR/dHUKY7pvAALl+fwfg0G24XRtaMi18DQT7kMxzI8WJa9jwrb3lPCEav39WVt8AFHUZd34z01oWvrd1SA7s5PjQ0KnJfrF3V+Cek58PwT0gpm2pxYLfw4X27+rdD90aWLCxYw9FIDFuWtUmetYfdhmEGNvjQ9kh9NvvAPNyV+OaRAQmSCWCirPXjd8u2moyDAdBMDHqO1WttcepX5NpmYv0TNFAHpoQyvakb9Rw4FqGQn1P4UG1E2n8G9uVHUhm0dU0S/LYR31wWLbolglsST3GD458lR+g+4Kx2MGB62WG0hL/3EaydxHGj5VxsCg/ExMQNA==
  template:
    metadata:
      creationTimestamp: null
      name: registry-credential
      namespace: fast-api
    type: kubernetes.io/dockerconfigjson

